export default {
  light: {
    primary: '#ff0000',
    background: '#EFEFEF',
    surface: '#FFFFFF',
    container_surface: '#DCDCDC',
    textPrimary: '#212121',
    textPrimaryReverse: '#FFFFFF',
    textSecondary: '#DCDCDC',
    accent: '#457B9D',
    buttonDefault: '#1E1E1E',
    buttonActive: '#C92A34',
    textBubbleOwn: '#ff0000',
    textBubbleOther: '#2C2C2C',
    borderColor: '#2A2A2A',
  },
  dark: {
    primary: '#ff0000',
    background: '#121212',
    surface: '#1E1E1E',
    container_surface: '#1E1E1E',
    textPrimary: '#FFFFFF',
    textPrimaryReverse: '#212121',
    textSecondary: '#BDBDBD',
    accent: '#A8DADC',
    buttonDefault: '#EFEFEF',
    buttonActive: '#FF4D5A',
    textBubbleOwn: '#ff0000',
    textBubbleOther: '#2C2C2C',
    borderColor: '#2A2A2A',
  },
  default: {
    primary: '#ff0000',
    borderColor: '#E0E0E0',
    defaultTextPrimary: '#212121',
  },
};

// old primary color:
// primary: '#E63946',
